services:
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    expose:
      - "80"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # Internal routing, not exposed to host
    expose:
      - "3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Internal routing, not exposed to host
    expose:
      - "4000"
